from __future__ import annotations

CONTEXT_SEED = [
    ("person_profile", "Julian Shelton", "Founder, author, investor, and systems architect building public proof through real estate, AI systems, books, and operating tools.", 100),
    ("mission", "Primary mission", "Build durable assets, cash flow, leverage, and freedom under Grim Empire Holdings LLC while documenting the climb in real time.", 100),
    ("mission", "Long-term embodied assistant", "Develop Maya and GrimBot toward a safe, affordable robot butler and eventual synth platform.", 70),
    ("venture", "Grim Empire Holdings LLC", "The holding-company and operating-philosophy layer connecting Julian's ventures, projects, books, systems, and long-term wealth architecture.", 95),
    ("venture", "Real estate acquisitions", "The primary cash-flow vehicle focused on distressed properties, wholesaling, buyer relationships, and disciplined deal analysis.", 100),
    ("venture", "Grim Curriculum", "Julian's self-directed education map built from books, mentors, sales, failed attempts, work, and business experiments.", 65),
    ("priority", "Revenue stabilization", "Stabilize cash flow and revenue before expanding the architecture faster than execution.", 100),
    ("priority", "Real estate deal flow", "Find and analyze better real estate opportunities and strengthen buyer relationships.", 98),
    ("priority", "Ground systems in use", "Use live operating friction to guide product development instead of adding speculative scope.", 90),
    ("relationship", "Julian Prime", "Strategic identity and second-mind layer. Owns direction, identity, and high-level judgment.", 100),
    ("relationship", "Maya", "Chief of Staff and operator. Organizes context, priorities, decisions, and follow-through for Julian.", 100),
    ("relationship", "GrimBot", "Embodied system and future robot shell. Physical assistance is one domain, not Maya's primary worldview.", 90),
    ("relationship", "Board", "Future specialist-agent layer for bounded domain expertise and review.", 60),
    ("protocol", "Protect the Asset", "Protect Julian, family assets, time, attention, reputation, and strategic options.", 100),
    ("protocol", "Family asset protocols", "Treat family protection, asset structure, and long-term stewardship as first-class constraints.", 95),
    ("belief", "Useful before ceremonial", "Memory and systems matter only when they improve decisions, action, or continuity.", 90),
    ("constraint", "Current operating constraint", "Capital, validation, prioritization, and revenue stability constrain how many projects can move at once.", 100),
    ("current_bottleneck", "Portfolio-wide bottleneck", "Prioritization and real-world validation are the shared bottlenecks across the active project portfolio.", 95),
    ("next_action", "Portfolio-wide next action", "Capture live friction, choose the highest-revenue next move, and validate before expanding scope.", 100),
]


PROJECT_SEED = [
    {
        "name": "Real Estate Acquisitions",
        "status": "active",
        "priority": 100,
        "current_bottleneck": "Capital, consistent deal flow, disciplined analysis, and buyer matching.",
        "next_action": "Find and analyze the strongest current deal opportunity and advance buyer conversations.",
        "related_entities": ["Grim Empire Holdings LLC", "GrimOS", "BirdDash"],
    },
    {
        "name": "GrimBot Butler OS",
        "status": "building",
        "priority": 82,
        "current_bottleneck": "Real-world operator testing and keeping Chief of Staff context accurate before hardware.",
        "next_action": "Log friction from using Maya Console in real work before adding hardware.",
        "related_entities": ["Maya", "Maya Console", "Julian Prime", "BioStructure"],
    },
    {
        "name": "Maya Console",
        "status": "building",
        "priority": 84,
        "current_bottleneck": "Real daily use is needed to expose missing, stale, or incorrectly ranked context.",
        "next_action": "Use the console for real briefings and record every incorrect or missing signal.",
        "related_entities": ["GrimBot Butler OS", "Maya", "Julian Prime"],
    },
    {
        "name": "GrimOS",
        "status": "building",
        "priority": 78,
        "current_bottleneck": "The public shell needs narrower workflows grounded in real acquisition activity.",
        "next_action": "Tighten one live acquisition workflow around deal analysis and buyer criteria.",
        "related_entities": ["Real Estate Acquisitions", "Grim Empire Holdings LLC"],
    },
    {
        "name": "BioStructure",
        "status": "building",
        "priority": 72,
        "current_bottleneck": "The private memory architecture must stay action-oriented rather than ceremonial.",
        "next_action": "Clarify the capture, relate, decide, and handoff operating loop.",
        "related_entities": ["Maya", "Julian Prime", "GrimBot Butler OS"],
    },
    {
        "name": "CrewShift Pro",
        "status": "building",
        "priority": 65,
        "current_bottleneck": "Needs a narrow customer-validated foreman workflow.",
        "next_action": "Refine the demo around on-site attendance, missing workers, reassignment, and reporting.",
        "related_entities": ["AutoShift"],
    },
    {
        "name": "AutoShift",
        "status": "experiment",
        "priority": 45,
        "current_bottleneck": "Buyer validation and a simpler first warehouse wedge.",
        "next_action": "Hold as a design reference until a tighter customer discovery path exists.",
        "related_entities": ["CrewShift Pro"],
    },
    {
        "name": "BirdDash",
        "status": "building",
        "priority": 70,
        "current_bottleneck": "The wholesale lead dashboard needs validation on live acquisition data and hardened data and AI integration.",
        "next_action": "Run one real lead batch through CSV import, scoring, review, and open or taken tracking.",
        "related_entities": ["Real Estate Acquisitions", "GrimOS"],
    },
    {
        "name": "Grim Curriculum",
        "status": "active",
        "priority": 60,
        "current_bottleneck": "The learning map needs to stay connected to current decisions and public proof.",
        "next_action": "Document only lessons that materially change strategy or execution.",
        "related_entities": ["Julian Shelton", "Grim Empire Holdings LLC"],
    },
]
